# SOLEN minimal Starship theme (optional)

add_newline = false
format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration\n$character"

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "@[$hostname](dimmed) "

[directory]
truncate_to_repo = false
style = "cyan"

[character]
success_symbol = "❯"
error_symbol = "❯"
vicmd_symbol = "❮"

